version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - gosec
    - gocyclo
    - goconst
    - misspell
    - unconvert
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports
